// <auto-generated />
using System;
using DockerUpdateGuard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DockerUpdateGuard.Data.Migrations
{
    [DbContext(typeof(DockerUpdateGuardDbContext))]
    [Migration("20260429051826_Update3")]
    partial class Update3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DockerUpdateGuard.Data.Entities.ContainerActionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ContainerSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DockerInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("PortainerEndpointId")
                        .HasColumnType("uuid");

                    b.Property<string>("PortainerTaskId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ResourceType")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContainerSnapshotId");

                    b.HasIndex("DockerInstanceId", "RequestedAtUtc");

                    b.HasIndex("PortainerEndpointId", "RequestedAtUtc");

                    b.ToTable("ContainerActionRuns", (string)null);
                });

            modelBuilder.Entity("DockerUpdateGuard.Data.Entities.ContainerSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvailableUpdateVersionTag")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ComposeProject")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ContainerId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("DockerInstanceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ImageVersionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResolvedVersionTag")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ScanRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("ServiceName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("StackName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UpdateAssessmentMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("UpdateAssessmentStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ImageVersionId");

                    b.HasIndex("ScanRunId");

                    b.HasIndex("DockerInstanceId", "ContainerId", "RecordedAtUtc");

                    b.ToTable("ContainerSnapshots", (string)null);
                });

            modelBuilder.Entity("DockerUpdateGuard.Data.Entities.DockerInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ConnectionKind")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EndpointUri")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("SkipCertificateValidation")
                        .HasColumnType("boolean");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DockerInstances", (string)null);
                });

            modelBuilder.Entity("DockerUpdateGuard.Data.Entities.DockerInstanceResourceSample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ContainerCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("CpuPercent")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<Guid>("DockerInstanceId")
                        .HasColumnType("uuid");

                    b.Property<long>("MemoryLimitBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("MemoryUsageBytes")
                        .HasColumnType("bigint");

                    b.Property<decimal>("NetworkRxBytesPerSecond")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)");

                    b.Property<long>("NetworkRxBytesTotal")
                        .HasColumnType("bigint");

                    b.Property<decimal>("NetworkTxBytesPerSecond")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)");

                    b.Property<long>("NetworkTxBytesTotal")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DockerInstanceId", "RecordedAtUtc");

                    b.ToTable("DockerInstanceResourceSamples", (string)null);
                });

            modelBuilder.Entity("DockerUpdateGuard.Data.Entities.ImageRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BaseImageVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChildImageVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Depth")
                        .HasColumnType("integer");

                    b.Property<int>("RelationshipType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ScanRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("BaseImageVersionId");

                    b.HasIndex("ChildImageVersionId");

                    b.HasIndex("ScanRunId");

                    b.HasIndex("ChildImageVersionId", "BaseImageVersionId", "Depth", "RelationshipType")
                        .IsUnique();

                    b.ToTable("ImageRelationships", null, t =>
                        {
                            t.HasCheckConstraint("CK_ImageRelationships_ChildAndBaseDifferent", "\"ChildImageVersionId\" <> \"BaseImageVersionId\"");

                            t.HasCheckConstraint("CK_ImageRelationships_DepthGreaterThanZero", "\"Depth\" > 0");
                        });
                });

            modelBuilder.Entity("DockerUpdateGuard.Data.Entities.ImageVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Digest")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RegistryRepositoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("VulnerabilityAssessmentCheckedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VulnerabilityAssessmentMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("VulnerabilityAssessmentSource")
                        .HasColumnType("integer");

                    b.Property<int>("VulnerabilityAssessmentStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RegistryRepositoryId", "Tag", "Digest")
                        .IsUnique();

                    b.ToTable("ImageVersions", (string)null);
                });

            modelBuilder.Entity("DockerUpdateGuard.Data.Entities.ObservedImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CurrentImageVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CurrentImageVersionId");

                    b.ToTable("ObservedImages", (string)null);
                });

            modelBuilder.Entity("DockerUpdateGuard.Data.Entities.PortainerEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DockerInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalEndpointId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DockerInstanceId")
                        .IsUnique();

                    b.ToTable("PortainerEndpoints", (string)null);
                });

            modelBuilder.Entity("DockerUpdateGuard.Data.Entities.RegistryRepository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Registry")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Repository")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Registry", "Repository")
                        .IsUnique();

                    b.ToTable("RegistryRepositories", (string)null);
                });

            modelBuilder.Entity("DockerUpdateGuard.Data.Entities.RuntimeContainerResourceSample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContainerId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("CpuPercent")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<Guid>("DockerInstanceId")
                        .HasColumnType("uuid");

                    b.Property<long>("MemoryLimitBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("MemoryUsageBytes")
                        .HasColumnType("bigint");

                    b.Property<decimal>("NetworkRxBytesPerSecond")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)");

                    b.Property<long>("NetworkRxBytesTotal")
                        .HasColumnType("bigint");

                    b.Property<decimal>("NetworkTxBytesPerSecond")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)");

                    b.Property<long>("NetworkTxBytesTotal")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DockerInstanceId", "ContainerId", "RecordedAtUtc");

                    b.ToTable("RuntimeContainerResourceSamples", (string)null);
                });

            modelBuilder.Entity("DockerUpdateGuard.Data.Entities.RuntimeContainerTagSelection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContainerId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Digest")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("DockerInstanceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RegistryRepositoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("SelectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("RegistryRepositoryId");

                    b.HasIndex("DockerInstanceId", "ContainerId")
                        .IsUnique();

                    b.ToTable("RuntimeContainerTagSelections", (string)null);
                });

            modelBuilder.Entity("DockerUpdateGuard.Data.Entities.ScanRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DiagnosticJson")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid?>("DockerInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("ObservedImageId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TriggerSource")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DockerInstanceId");

                    b.HasIndex("ObservedImageId");

                    b.HasIndex("Type", "Status", "StartedAtUtc");

                    b.ToTable("ScanRuns", (string)null);
                });

            modelBuilder.Entity("DockerUpdateGuard.Data.Entities.TagCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Digest")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsRecommended")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UpdateFindingId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UpdateFindingId", "Tag", "Digest")
                        .IsUnique();

                    b.ToTable("TagCandidates", (string)null);
                });

            modelBuilder.Entity("DockerUpdateGuard.Data.Entities.UpdateFinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContainerSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("DetectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ObservedImageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RecommendedImageVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ScanRunId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubjectImageVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecommendedImageVersionId");

                    b.HasIndex("ScanRunId");

                    b.HasIndex("ContainerSnapshotId", "IsActive");

                    b.HasIndex("ObservedImageId", "IsActive");

                    b.HasIndex("SubjectImageVersionId", "IsActive");

                    b.ToTable("UpdateFindings", (string)null);
                });

            modelBuilder.Entity("DockerUpdateGuard.Data.Entities.VulnerabilityFinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdvisoryId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AffectedPackage")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("CvssScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTimeOffset>("DetectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FixedVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ImageVersionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ReferenceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ScanRunId")
                        .HasColumnType("uuid");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("ScanRunId");

                    b.HasIndex("ImageVersionId", "Severity", "IsActive");

                    b.HasIndex("ImageVersionId", "AdvisoryId", "AffectedPackage", "FixedVersion")
                        .IsUnique();

                    b.ToTable("VulnerabilityFindings", (string)null);
                });

            modelBuilder.Entity("DockerUpdateGuard.Data.Entities.ContainerActionRun", b =>
                {
                    b.HasOne("DockerUpdateGuard.Data.Entities.ContainerSnapshot", "ContainerSnapshot")
                        .WithMany("ContainerActionRuns")
                        .HasForeignKey("ContainerSnapshotId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DockerUpdateGuard.Data.Entities.DockerInstance", "DockerInstance")
                        .WithMany("ContainerActionRuns")
                        .HasForeignKey("DockerInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DockerUpdateGuard.Data.Entities.PortainerEndpoint", "PortainerEndpoint")
                        .WithMany("ContainerActionRuns")
                        .HasForeignKey("PortainerEndpointId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ContainerSnapshot");

                    b.Navigation("DockerInstance");

                    b.Navigation("PortainerEndpoint");
                });

            modelBuilder.Entity("DockerUpdateGuard.Data.Entities.ContainerSnapshot", b =>
                {
                    b.HasOne("DockerUpdateGuard.Data.Entities.DockerInstance", "DockerInstance")
                        .WithMany("ContainerSnapshots")
                        .HasForeignKey("DockerInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DockerUpdateGuard.Data.Entities.ImageVersion", "ImageVersion")
                        .WithMany("ContainerSnapshots")
                        .HasForeignKey("ImageVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DockerUpdateGuard.Data.Entities.ScanRun", "ScanRun")
                        .WithMany("ContainerSnapshots")
                        .HasForeignKey("ScanRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DockerInstance");

                    b.Navigation("ImageVersion");

                    b.Navigation("ScanRun");
                });

            modelBuilder.Entity("DockerUpdateGuard.Data.Entities.DockerInstanceResourceSample", b =>
                {
                    b.HasOne("DockerUpdateGuard.Data.Entities.DockerInstance", "DockerInstance")
                        .WithMany()
                        .HasForeignKey("DockerInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DockerInstance");
                });

            modelBuilder.Entity("DockerUpdateGuard.Data.Entities.ImageRelationship", b =>
                {
                    b.HasOne("DockerUpdateGuard.Data.Entities.ImageVersion", "BaseImageVersion")
                        .WithMany("BaseRelationships")
                        .HasForeignKey("BaseImageVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DockerUpdateGuard.Data.Entities.ImageVersion", "ChildImageVersion")
                        .WithMany("ChildRelationships")
                        .HasForeignKey("ChildImageVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DockerUpdateGuard.Data.Entities.ScanRun", "ScanRun")
                        .WithMany("ImageRelationships")
                        .HasForeignKey("ScanRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BaseImageVersion");

                    b.Navigation("ChildImageVersion");

                    b.Navigation("ScanRun");
                });

            modelBuilder.Entity("DockerUpdateGuard.Data.Entities.ImageVersion", b =>
                {
                    b.HasOne("DockerUpdateGuard.Data.Entities.RegistryRepository", "RegistryRepository")
                        .WithMany("ImageVersions")
                        .HasForeignKey("RegistryRepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegistryRepository");
                });

            modelBuilder.Entity("DockerUpdateGuard.Data.Entities.ObservedImage", b =>
                {
                    b.HasOne("DockerUpdateGuard.Data.Entities.ImageVersion", "CurrentImageVersion")
                        .WithMany("ObservedImages")
                        .HasForeignKey("CurrentImageVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentImageVersion");
                });

            modelBuilder.Entity("DockerUpdateGuard.Data.Entities.PortainerEndpoint", b =>
                {
                    b.HasOne("DockerUpdateGuard.Data.Entities.DockerInstance", "DockerInstance")
                        .WithOne("PortainerEndpoint")
                        .HasForeignKey("DockerUpdateGuard.Data.Entities.PortainerEndpoint", "DockerInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DockerInstance");
                });

            modelBuilder.Entity("DockerUpdateGuard.Data.Entities.RuntimeContainerResourceSample", b =>
                {
                    b.HasOne("DockerUpdateGuard.Data.Entities.DockerInstance", "DockerInstance")
                        .WithMany()
                        .HasForeignKey("DockerInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DockerInstance");
                });

            modelBuilder.Entity("DockerUpdateGuard.Data.Entities.RuntimeContainerTagSelection", b =>
                {
                    b.HasOne("DockerUpdateGuard.Data.Entities.DockerInstance", "DockerInstance")
                        .WithMany()
                        .HasForeignKey("DockerInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DockerUpdateGuard.Data.Entities.RegistryRepository", "RegistryRepository")
                        .WithMany()
                        .HasForeignKey("RegistryRepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DockerInstance");

                    b.Navigation("RegistryRepository");
                });

            modelBuilder.Entity("DockerUpdateGuard.Data.Entities.ScanRun", b =>
                {
                    b.HasOne("DockerUpdateGuard.Data.Entities.DockerInstance", "DockerInstance")
                        .WithMany("ScanRuns")
                        .HasForeignKey("DockerInstanceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DockerUpdateGuard.Data.Entities.ObservedImage", "ObservedImage")
                        .WithMany("ScanRuns")
                        .HasForeignKey("ObservedImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DockerInstance");

                    b.Navigation("ObservedImage");
                });

            modelBuilder.Entity("DockerUpdateGuard.Data.Entities.TagCandidate", b =>
                {
                    b.HasOne("DockerUpdateGuard.Data.Entities.UpdateFinding", "UpdateFinding")
                        .WithMany("TagCandidates")
                        .HasForeignKey("UpdateFindingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UpdateFinding");
                });

            modelBuilder.Entity("DockerUpdateGuard.Data.Entities.UpdateFinding", b =>
                {
                    b.HasOne("DockerUpdateGuard.Data.Entities.ContainerSnapshot", "ContainerSnapshot")
                        .WithMany("UpdateFindings")
                        .HasForeignKey("ContainerSnapshotId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DockerUpdateGuard.Data.Entities.ObservedImage", "ObservedImage")
                        .WithMany("UpdateFindings")
                        .HasForeignKey("ObservedImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DockerUpdateGuard.Data.Entities.ImageVersion", "RecommendedImageVersion")
                        .WithMany("RecommendedByUpdateFindings")
                        .HasForeignKey("RecommendedImageVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DockerUpdateGuard.Data.Entities.ScanRun", "ScanRun")
                        .WithMany("UpdateFindings")
                        .HasForeignKey("ScanRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DockerUpdateGuard.Data.Entities.ImageVersion", "SubjectImageVersion")
                        .WithMany("SubjectUpdateFindings")
                        .HasForeignKey("SubjectImageVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContainerSnapshot");

                    b.Navigation("ObservedImage");

                    b.Navigation("RecommendedImageVersion");

                    b.Navigation("ScanRun");

                    b.Navigation("SubjectImageVersion");
                });

            modelBuilder.Entity("DockerUpdateGuard.Data.Entities.VulnerabilityFinding", b =>
                {
                    b.HasOne("DockerUpdateGuard.Data.Entities.ImageVersion", "ImageVersion")
                        .WithMany("VulnerabilityFindings")
                        .HasForeignKey("ImageVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DockerUpdateGuard.Data.Entities.ScanRun", "ScanRun")
                        .WithMany("VulnerabilityFindings")
                        .HasForeignKey("ScanRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ImageVersion");

                    b.Navigation("ScanRun");
                });

            modelBuilder.Entity("DockerUpdateGuard.Data.Entities.ContainerSnapshot", b =>
                {
                    b.Navigation("ContainerActionRuns");

                    b.Navigation("UpdateFindings");
                });

            modelBuilder.Entity("DockerUpdateGuard.Data.Entities.DockerInstance", b =>
                {
                    b.Navigation("ContainerActionRuns");

                    b.Navigation("ContainerSnapshots");

                    b.Navigation("PortainerEndpoint");

                    b.Navigation("ScanRuns");
                });

            modelBuilder.Entity("DockerUpdateGuard.Data.Entities.ImageVersion", b =>
                {
                    b.Navigation("BaseRelationships");

                    b.Navigation("ChildRelationships");

                    b.Navigation("ContainerSnapshots");

                    b.Navigation("ObservedImages");

                    b.Navigation("RecommendedByUpdateFindings");

                    b.Navigation("SubjectUpdateFindings");

                    b.Navigation("VulnerabilityFindings");
                });

            modelBuilder.Entity("DockerUpdateGuard.Data.Entities.ObservedImage", b =>
                {
                    b.Navigation("ScanRuns");

                    b.Navigation("UpdateFindings");
                });

            modelBuilder.Entity("DockerUpdateGuard.Data.Entities.PortainerEndpoint", b =>
                {
                    b.Navigation("ContainerActionRuns");
                });

            modelBuilder.Entity("DockerUpdateGuard.Data.Entities.RegistryRepository", b =>
                {
                    b.Navigation("ImageVersions");
                });

            modelBuilder.Entity("DockerUpdateGuard.Data.Entities.ScanRun", b =>
                {
                    b.Navigation("ContainerSnapshots");

                    b.Navigation("ImageRelationships");

                    b.Navigation("UpdateFindings");

                    b.Navigation("VulnerabilityFindings");
                });

            modelBuilder.Entity("DockerUpdateGuard.Data.Entities.UpdateFinding", b =>
                {
                    b.Navigation("TagCandidates");
                });
#pragma warning restore 612, 618
        }
    }
}
