// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Minor Code Smell", "S1125:Boolean literals should not be redundant", Justification = "SonarCloud", Scope = "module")]
[assembly: SuppressMessage("Minor Code Smell", "S2325:Methods and properties that don't access instance data should be static", Justification = "SonarCloud", Scope = "module")]

[assembly: SuppressMessage("Major Bug", "S1244:Floating point numbers should not be tested for equality", Justification = "SonarCloud", Scope = "module")]

[assembly: SuppressMessage("Major Code Smell", "S6968:Actions that return a value should be annotated with ProducesResponseTypeAttribute containing the return type", Justification = "SonarCloud", Scope = "module")]

[assembly: SuppressMessage("Vulnerability", "S4830:Server certificates should be verified during SSL/TLS connections", Justification = "Opt-in administrator setting (DockerInstanceOptions.SkipCertificateValidation); the bypass is gated behind explicit configuration and a runtime warning is logged whenever it is active.", Scope = "member", Target = "~M:DockerUpdateGuard.Docker.DockerInstanceClient.CreateHttpClient(DockerUpdateGuard.Configuration.DockerInstanceOptions,System.Uri,Microsoft.Extensions.Logging.ILogger)~System.Net.Http.HttpClient")]

[assembly: SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "Required placeholder base address; the request never reaches localhost because SocketsHttpHandler.ConnectCallback routes the connection to the configured Unix socket.", Scope = "member", Target = "~M:DockerUpdateGuard.Docker.DockerInstanceClient.CreateUnixSocketHttpClient(System.String)~System.Net.Http.HttpClient")]
[assembly: SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "Required placeholder base address; the request never reaches localhost because SocketsHttpHandler.ConnectCallback routes the connection to the configured named pipe.", Scope = "member", Target = "~M:DockerUpdateGuard.Docker.DockerInstanceClient.CreateNamedPipeHttpClient(System.Uri)~System.Net.Http.HttpClient")]
[assembly: SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "Required placeholder engine URI for the unix and npipe schemes; the actual endpoint is the configured socket or pipe, which is dialed by SocketsHttpHandler.ConnectCallback.", Scope = "member", Target = "~M:DockerUpdateGuard.Docker.DockerInstanceClient.TryCreateEngineUri(DockerUpdateGuard.Configuration.DockerInstanceOptions,System.Uri@)~System.Boolean")]

[assembly: SuppressMessage("Major Code Smell", "S107:Methods should not have too many parameters", Justification = "Constructor injection of the orchestrated services; splitting the dependencies into aggregate types would hide the composition without reducing it.", Scope = "member", Target = "~M:DockerUpdateGuard.Images.ImageScanOrchestrator.#ctor(DockerUpdateGuard.ApplicationTelemetry,DockerUpdateGuard.Images.Interfaces.IBaseImageResolver,DockerUpdateGuard.Data.DockerUpdateGuardDbContext,DockerUpdateGuard.Images.Interfaces.IDerivedBaseRuntimeDetector,DockerUpdateGuard.Images.Interfaces.IDotNetReleaseMetadataService,DockerUpdateGuard.Images.Interfaces.INginxReleaseMetadataService,DockerUpdateGuard.Data.Repositories.IImageCatalogRepository,DockerUpdateGuard.Images.Interfaces.IImageReferenceParser,Microsoft.Extensions.Logging.ILogger{DockerUpdateGuard.Images.ImageScanOrchestrator},DockerUpdateGuard.Images.Interfaces.IRegistryMetadataService)")]
[assembly: SuppressMessage("Major Code Smell", "S107:Methods should not have too many parameters", Justification = "Constructor injection of the orchestrated services; splitting the dependencies into aggregate types would hide the composition without reducing it.", Scope = "member", Target = "~M:DockerUpdateGuard.Images.RuntimeContainerScanOrchestrator.#ctor(DockerUpdateGuard.ApplicationTelemetry,DockerUpdateGuard.Data.DockerUpdateGuardDbContext,DockerUpdateGuard.Docker.IDockerInstanceClient,DockerUpdateGuard.Images.Interfaces.IDerivedBaseRuntimeDetector,DockerUpdateGuard.Images.Interfaces.IDotNetReleaseMetadataService,DockerUpdateGuard.Images.Interfaces.INginxReleaseMetadataService,DockerUpdateGuard.Data.Repositories.IImageCatalogRepository,DockerUpdateGuard.Images.Interfaces.IImageReferenceParser,DockerUpdateGuard.Images.Interfaces.IInstanceDiscoveryService,Microsoft.Extensions.Logging.ILogger{DockerUpdateGuard.Images.RuntimeContainerScanOrchestrator},Microsoft.Extensions.Options.IOptionsMonitor{DockerUpdateGuard.Configuration.DockerUpdateGuardOptions},DockerUpdateGuard.Images.Interfaces.IRegistryMetadataService,DockerUpdateGuard.Images.Interfaces.IUpdateDetectionService)")]

[assembly: SuppressMessage("Usage", "CA2213:Disposable fields should be disposed", Justification = "MudThemeProvider is a child Razor component captured via @ref; the Blazor render tree owns and disposes it, not the parent layout.", Scope = "member", Target = "~F:DockerUpdateGuard.Components.Layout.MainLayout._themeProvider")]